/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-05-20")
public class Resultado implements org.apache.thrift.TBase<Resultado, Resultado._Fields>, java.io.Serializable, Cloneable, Comparable<Resultado> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Resultado");

  private static final org.apache.thrift.protocol.TField RESULTADO_FIELD_DESC = new org.apache.thrift.protocol.TField("resultado", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField MENSAJE_ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("mensajeError", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ResultadoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ResultadoTupleSchemeFactory();

  public double resultado; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String mensajeError; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESULTADO((short)1, "resultado"),
    MENSAJE_ERROR((short)2, "mensajeError");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESULTADO
          return RESULTADO;
        case 2: // MENSAJE_ERROR
          return MENSAJE_ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RESULTADO_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESULTADO, new org.apache.thrift.meta_data.FieldMetaData("resultado", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.MENSAJE_ERROR, new org.apache.thrift.meta_data.FieldMetaData("mensajeError", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Resultado.class, metaDataMap);
  }

  public Resultado() {
  }

  public Resultado(
    double resultado,
    java.lang.String mensajeError)
  {
    this();
    this.resultado = resultado;
    setResultadoIsSet(true);
    this.mensajeError = mensajeError;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Resultado(Resultado other) {
    __isset_bitfield = other.__isset_bitfield;
    this.resultado = other.resultado;
    if (other.isSetMensajeError()) {
      this.mensajeError = other.mensajeError;
    }
  }

  public Resultado deepCopy() {
    return new Resultado(this);
  }

  @Override
  public void clear() {
    setResultadoIsSet(false);
    this.resultado = 0.0;
    this.mensajeError = null;
  }

  public double getResultado() {
    return this.resultado;
  }

  public Resultado setResultado(double resultado) {
    this.resultado = resultado;
    setResultadoIsSet(true);
    return this;
  }

  public void unsetResultado() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RESULTADO_ISSET_ID);
  }

  /** Returns true if field resultado is set (has been assigned a value) and false otherwise */
  public boolean isSetResultado() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RESULTADO_ISSET_ID);
  }

  public void setResultadoIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RESULTADO_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMensajeError() {
    return this.mensajeError;
  }

  public Resultado setMensajeError(@org.apache.thrift.annotation.Nullable java.lang.String mensajeError) {
    this.mensajeError = mensajeError;
    return this;
  }

  public void unsetMensajeError() {
    this.mensajeError = null;
  }

  /** Returns true if field mensajeError is set (has been assigned a value) and false otherwise */
  public boolean isSetMensajeError() {
    return this.mensajeError != null;
  }

  public void setMensajeErrorIsSet(boolean value) {
    if (!value) {
      this.mensajeError = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case RESULTADO:
      if (value == null) {
        unsetResultado();
      } else {
        setResultado((java.lang.Double)value);
      }
      break;

    case MENSAJE_ERROR:
      if (value == null) {
        unsetMensajeError();
      } else {
        setMensajeError((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RESULTADO:
      return getResultado();

    case MENSAJE_ERROR:
      return getMensajeError();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RESULTADO:
      return isSetResultado();
    case MENSAJE_ERROR:
      return isSetMensajeError();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Resultado)
      return this.equals((Resultado)that);
    return false;
  }

  public boolean equals(Resultado that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_resultado = true;
    boolean that_present_resultado = true;
    if (this_present_resultado || that_present_resultado) {
      if (!(this_present_resultado && that_present_resultado))
        return false;
      if (this.resultado != that.resultado)
        return false;
    }

    boolean this_present_mensajeError = true && this.isSetMensajeError();
    boolean that_present_mensajeError = true && that.isSetMensajeError();
    if (this_present_mensajeError || that_present_mensajeError) {
      if (!(this_present_mensajeError && that_present_mensajeError))
        return false;
      if (!this.mensajeError.equals(that.mensajeError))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(resultado);

    hashCode = hashCode * 8191 + ((isSetMensajeError()) ? 131071 : 524287);
    if (isSetMensajeError())
      hashCode = hashCode * 8191 + mensajeError.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Resultado other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetResultado()).compareTo(other.isSetResultado());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResultado()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resultado, other.resultado);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMensajeError()).compareTo(other.isSetMensajeError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMensajeError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mensajeError, other.mensajeError);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Resultado(");
    boolean first = true;

    sb.append("resultado:");
    sb.append(this.resultado);
    first = false;
    if (!first) sb.append(", ");
    sb.append("mensajeError:");
    if (this.mensajeError == null) {
      sb.append("null");
    } else {
      sb.append(this.mensajeError);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ResultadoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ResultadoStandardScheme getScheme() {
      return new ResultadoStandardScheme();
    }
  }

  private static class ResultadoStandardScheme extends org.apache.thrift.scheme.StandardScheme<Resultado> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Resultado struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESULTADO
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.resultado = iprot.readDouble();
              struct.setResultadoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MENSAJE_ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mensajeError = iprot.readString();
              struct.setMensajeErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Resultado struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RESULTADO_FIELD_DESC);
      oprot.writeDouble(struct.resultado);
      oprot.writeFieldEnd();
      if (struct.mensajeError != null) {
        oprot.writeFieldBegin(MENSAJE_ERROR_FIELD_DESC);
        oprot.writeString(struct.mensajeError);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ResultadoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ResultadoTupleScheme getScheme() {
      return new ResultadoTupleScheme();
    }
  }

  private static class ResultadoTupleScheme extends org.apache.thrift.scheme.TupleScheme<Resultado> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Resultado struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetResultado()) {
        optionals.set(0);
      }
      if (struct.isSetMensajeError()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetResultado()) {
        oprot.writeDouble(struct.resultado);
      }
      if (struct.isSetMensajeError()) {
        oprot.writeString(struct.mensajeError);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Resultado struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.resultado = iprot.readDouble();
        struct.setResultadoIsSet(true);
      }
      if (incoming.get(1)) {
        struct.mensajeError = iprot.readString();
        struct.setMensajeErrorIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

